# Try out a clean installation of this configuration bundle on a
# couple of Emacs versions.  Installation also evaluates most of the
# elisp code used so it's an indication of everything working.

name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
          - snapshot

    steps:

      - name: Setup Emacs
        uses: purcell/setup-emacs@v6.0
        with:
          version: ${{ matrix.emacs_version }}
    
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install dependencies
        run: make install
